language: scala

jdk: openjdk8

jobs:
  include:
    - test

jobs:
  include:
    - stage: test
      script: cd play-cxf && sbt +test
      name: "Run tests for Scala 2.11, Scala 2.12 and Scala 2.13"

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - "$HOME/.coursier/cache"
    - "$HOME/.ivy2/cache"
    - "$HOME/.ivy2/local"
    - "$HOME/.jabba/jdk"
    - "$HOME/.sbt"

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
